// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FileTransport.proto

package com.li.rpc;

public interface FileInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.li.rpc.FileInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 index = 1;</code>
   * @return The index.
   */
  int getIndex();

  /**
   * <code>bytes arrs = 2;</code>
   * @return The arrs.
   */
  com.google.protobuf.ByteString getArrs();
}
