// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FileTransport.proto

package com.li.rpc;

public final class FileTransportApi {
  private FileTransportApi() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_li_rpc_FileInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_li_rpc_FileInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_li_rpc_Info_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_li_rpc_Info_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023FileTransport.proto\022\ncom.li.rpc\"\'\n\010Fil" +
      "eInfo\022\r\n\005index\030\001 \001(\005\022\014\n\004arrs\030\002 \001(\014\"\023\n\004In" +
      "fo\022\013\n\003msg\030\001 \001(\t2D\n\nRouteGuide\0226\n\010sendFil" +
      "e\022\024.com.li.rpc.FileInfo\032\020.com.li.rpc.Inf" +
      "o\"\000(\001B \n\ncom.li.rpcB\020FileTransportApiP\001b" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_li_rpc_FileInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_li_rpc_FileInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_li_rpc_FileInfo_descriptor,
        new java.lang.String[] { "Index", "Arrs", });
    internal_static_com_li_rpc_Info_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_li_rpc_Info_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_li_rpc_Info_descriptor,
        new java.lang.String[] { "Msg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
