// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FileTransport.proto

package com.li.rpc;

public interface InfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.li.rpc.Info)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string msg = 1;</code>
   * @return The msg.
   */
  java.lang.String getMsg();
  /**
   * <code>string msg = 1;</code>
   * @return The bytes for msg.
   */
  com.google.protobuf.ByteString
      getMsgBytes();
}
